/**
 *  States
 */

module.exports = {
    ALREADY_PLAYED: 'ALREADY_PLAYED',
    MISSED_HIT: 'MISSED_HIT',
    SHIP_TOUCHED: 'SHIP_TOUCHED',
    SHIP_DESTROYED: 'SHIP_DESTROYED',
    SHIP_ALL_DESTROYED: 'SHIP_ALL_DESTROYED'
}
